In [1]:
import pandas as pd

train = pd.read_csv("/Users/jeonmyeong-un/Desktop/KDT LIKELION/0712_std/dacon_prarking_demand_dataset/train.csv")
test = pd.read_csv("/Users/jeonmyeong-un/Desktop/KDT LIKELION/0712_std/dacon_prarking_demand_dataset/test.csv")
sub = pd.read_csv("/Users/jeonmyeong-un/Desktop/KDT LIKELION/0712_std/dacon_prarking_demand_dataset/sample_submission.csv")
age = pd.read_csv("/Users/jeonmyeong-un/Desktop/KDT LIKELION/0712_std/dacon_prarking_demand_dataset/age_gender_info.csv")

In [5]:
from sklearn.linear_model import LinearRegression

sel = ['총세대수']
X_train = train[sel]
X_test = test[sel]
y_train = train['등록차량수']

model = LinearRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)
pred

array([524.31256846, 524.31256846, 524.31256846, ..., 424.88994317,
       424.88994317, 424.88994317])

In [9]:
import numpy as np
test['등록차량수'] = pred
test['코드별차량수평균'] = test.groupby('단지코드')['등록차량수'].transform(np.mean)
test_new = test.drop_duplicates(['단지코드'], keep='first').reset_index()
test_new

,index,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,도보 10분거리 내 지하철역 수(환승노선 수 반영),도보 10분거리 내 버스정류장 수,단지내주차면수,등록차량수,코드별차량수평균
0,0,C1072,754,아파트,경기도,국민임대,39.79,116,14.0,H,22830000,189840,0.0,2.0,683.0,524.312568,524.312568
1,8,C1128,1354,아파트,경기도,국민임대,39.79,368,9.0,H,22830000,189840,0.0,3.0,1216.0,684.671641,684.671641
2,17,C1456,619,아파트,부산광역시,국민임대,33.40,82,18.0,A,19706000,156200,0.0,16.0,547.0,488.231777,488.231777
3,26,C1840,593,아파트,전라북도,국민임대,39.57,253,7.0,A,14418000,108130,0.0,3.0,543.0,481.282884,481.282884
4,30,C1332,1297,아파트,경기도,국민임대,39.99,282,11.0,H,28598000,203050,0.0,2.0,1112.0,669.437530,669.437530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,996,C2456,349,아파트,제주특별자치도,국민임대,26.44,24,17.0,H,6992000,117000,0.0,4.0,270.0,416.070194,416.070194
146,1000,C1266,596,아파트,충청북도,국민임대,26.94,164,35.0,H,8084000,149910,0.0,1.0,593.0,482.084679,482.084679
147,1005,C2152,120,아파트,강원도,영구임대,24.83,66,9.0,C,-,-,0.0,1.0,40.0,354.866481,354.866481
148,1007,C1267,675,아파트,경상남도,국민임대,24.87,28,38.0,H,6882000,104370,0.0,1.0,467.0,503.198624,503.198624
149,1018,C2189,382,아파트,전라북도,국민임대,29.19,96,45.0,H,6872000,106400,0.0,2.0,300.0,424.889943,424.889943